baseURL: https://izalimasec.github.io/
title: "Iza Lima | SecOps & Forense"
theme: hextra
languageCode: pt-br

params:
  navbar:
    title: "Iza Lima"
    displayLogo: true
  footer:
    displayCopyright: true
  blog:
    list:
      display: true
      showDate: true
      showReadingTime: true